# Files distributed to students (.ok & tests/ handled automatically)
sp21/hw/hw04.d: $(MATERIALS_DST)/sp21/hw/hw04/burrito.csv
sp21/hw/hw04.d: $(MATERIALS_DST)/sp21/hw/hw04/burritos_types.csv
sp21/hw/hw04.d: $(MATERIALS_DST)/sp21/hw/hw04/ratings.csv
sp21/hw/hw04.d: $(MATERIALS_DST)/sp21/hw/hw04/faculty.csv
sp21/hw/hw04.d: $(MATERIALS_DST)/sp21/hw/hw04/berkeley_faculty.csv