# Files distributed to students (.ok & tests/ handled automatically)
sp21/hw/hw09.d: $(MATERIALS_DST)/sp21/hw/hw09/waiting_times.csv
sp21/hw/hw09.d: $(MATERIALS_DST)/sp21/hw/hw09/smallrepvarhist.png
sp21/hw/hw09.d: $(MATERIALS_DST)/sp21/hw/hw09/reviews.csv
sp21/hw/hw09.d: $(MATERIALS_DST)/sp21/hw/hw09/more_reviews.csv
sp21/hw/hw09.d: $(MATERIALS_DST)/sp21/hw/hw09/population_waiting_times.csv
sp21/hw/hw09.d: $(MATERIALS_DST)/sp21/hw/hw09/one_sample.csv