# Files distributed to students (.ok & tests/ handled automatically)
sp21/project/project2.d: $(MATERIALS_DST)/sp21/project/project2/causes_of_death.csv
sp21/project/project2.d: $(MATERIALS_DST)/sp21/project/project2/serum_cholesterol.csv
sp21/project/project2.d: $(MATERIALS_DST)/sp21/project/project2/mortality_summary.csv
sp21/project/project2.d: $(MATERIALS_DST)/sp21/project/project2/framingham.csv
sp21/project/project2.d: $(MATERIALS_DST)/sp21/project/project2/bootstrap_rrs.csv
sp21/project/project2.d: $(MATERIALS_DST)/sp21/project/project2/bootstrap-HERS.png
sp21/project/project2.d: $(MATERIALS_DST)/sp21/project/project2/HERS-table.png
sp21/project/project2.d: $(MATERIALS_DST)/sp21/project/project2/NHS.csv
sp21/project/project2.d: $(MATERIALS_DST)/sp21/project/project2/hazardrate.png