# Files distributed to students (.ok & tests/ handled automatically)
sp21/hw/hw10.d: $(MATERIALS_DST)/sp21/hw/hw10/pten.csv
sp21/hw/hw10.d: $(MATERIALS_DST)/sp21/hw/hw10/normal1.png
sp21/hw/hw10.d: $(MATERIALS_DST)/sp21/hw/hw10/normal2.png
sp21/hw/hw10.d: $(MATERIALS_DST)/sp21/hw/hw10/virus-log-chart.jpg