# Files distributed to students (.ok & tests/ handled automatically)
sp21/project/project1.d: $(MATERIALS_DST)/sp21/project/project1/child_mortality.csv
sp21/project/project1.d: $(MATERIALS_DST)/sp21/project/project1/countries.csv
sp21/project/project1.d: $(MATERIALS_DST)/sp21/project/project1/fertility.csv
sp21/project/project1.d: $(MATERIALS_DST)/sp21/project/project1/life_expectancy.csv
sp21/project/project1.d: $(MATERIALS_DST)/sp21/project/project1/pew_population_projection.png
sp21/project/project1.d: $(MATERIALS_DST)/sp21/project/project1/population.csv
sp21/project/project1.d: $(MATERIALS_DST)/sp21/project/project1/poverty.csv