# Files distributed to students (.ok & tests/ handled automatically)
sp21/lab/lab01.d: $(MATERIALS_DST)/sp21/lab/lab01/error.jpg
sp21/lab/lab01.d: $(MATERIALS_DST)/sp21/lab/lab01/numberline_0.png
sp21/lab/lab01.d: $(MATERIALS_DST)/sp21/lab/lab01/numberline_1.png
sp21/lab/lab01.d: $(MATERIALS_DST)/sp21/lab/lab01/map.jpg