# Files distributed to students (.ok & tests/ handled automatically)
sp21/lab/lab02.d: $(MATERIALS_DST)/sp21/lab/lab02/world_population.csv
sp21/lab/lab02.d: $(MATERIALS_DST)/sp21/lab/lab02/imdb.csv
sp21/lab/lab02.d: $(MATERIALS_DST)/sp21/lab/lab02/farmers_markets.csv
sp21/lab/lab02.d: $(MATERIALS_DST)/sp21/lab/lab02/statement.png