# Files distributed to students (.ok & tests/ handled automatically)
sp21/lab/lab03.d: $(MATERIALS_DST)/sp21/lab/lab03/world_population.csv
sp21/lab/lab03.d: $(MATERIALS_DST)/sp21/lab/lab03/array_logarithm.jpg
sp21/lab/lab03.d: $(MATERIALS_DST)/sp21/lab/lab03/array_multiplication.jpg
sp21/lab/lab03.d: $(MATERIALS_DST)/sp21/lab/lab03/more_restaurant_bills.csv
sp21/lab/lab03.d: $(MATERIALS_DST)/sp21/lab/lab03/excel_array.jpg
sp21/lab/lab03.d: $(MATERIALS_DST)/sp21/lab/lab03/chaining_method_calls.png
sp21/lab/lab03.d: $(MATERIALS_DST)/sp21/lab/lab03/imdb.csv