# Files distributed to students (.ok & tests/ handled automatically)
sp21/hw/hw03.d: $(MATERIALS_DST)/sp21/hw/hw03/unemployment.csv
sp21/hw/hw03.d: $(MATERIALS_DST)/sp21/hw/hw03/nst-est2016-alldata.csv
sp21/hw/hw03.d: $(MATERIALS_DST)/sp21/hw/hw03/scatter.png
sp21/hw/hw03.d: $(MATERIALS_DST)/sp21/hw/hw03/var1.png
sp21/hw/hw03.d: $(MATERIALS_DST)/sp21/hw/hw03/var2.png
sp21/hw/hw03.d: $(MATERIALS_DST)/sp21/hw/hw03/var3.png
sp21/hw/hw03.d: $(MATERIALS_DST)/sp21/hw/hw03/boston.csv
sp21/hw/hw03.d: $(MATERIALS_DST)/sp21/hw/hw03/manila.csv