# Files distributed to students (.ok & tests/ handled automatically)
sp21/hw/hw06.d: $(MATERIALS_DST)/sp21/hw/hw06/player_data.csv
sp21/hw/hw06.d: $(MATERIALS_DST)/sp21/hw/hw06/salary_data.csv
sp21/hw/hw06.d: $(MATERIALS_DST)/sp21/hw/hw06/sample_salary_data.csv
sp21/hw/hw06.d: $(MATERIALS_DST)/sp21/hw/hw06/earthquakes_2019.csv