# Files distributed to students (.ok & tests/ handled automatically)
sp21/lab/lab04.d: $(MATERIALS_DST)/sp21/lab/lab04/raw_compensation.csv
sp21/lab/lab04.d: $(MATERIALS_DST)/sp21/lab/lab04/movies_by_year.csv
sp21/lab/lab04.d: $(MATERIALS_DST)/sp21/lab/lab04/apply.png