# Files distributed to students (.ok & tests/ handled automatically)
sp21/lab/lab05.d: $(MATERIALS_DST)/sp21/lab/lab05/Austen_PrideAndPrejudice.txt
sp21/lab/lab05.d: $(MATERIALS_DST)/sp21/lab/lab05/player_data.csv
sp21/lab/lab05.d: $(MATERIALS_DST)/sp21/lab/lab05/salary_data.csv
sp21/lab/lab05.d: $(MATERIALS_DST)/sp21/lab/lab05/small_srswor_salary.csv
sp21/lab/lab05.d: $(MATERIALS_DST)/sp21/lab/lab05/large_srswor_salary.csv
sp21/lab/lab05.d: $(MATERIALS_DST)/sp21/lab/lab05/comparisons.png
sp21/lab/lab05.d: $(MATERIALS_DST)/sp21/lab/lab05/nacho_reactions.png